---
title: 'RMarkdown:  In Class Assignment'
author: "Lindsey Smith"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## this line makes all the code show! 
  ## and these lines are comments - anything behind a '#' doesn't run!
  ## Everything above this is R code that we need to make the file run! We'll discuss it next class.
```


Reminder: We learned how to do these things in class today, but there is a "Markdown Help" page available in RStudio (and lots of help if you google). 


# In-class Activity, Markdown

**Do not skip reading this line** Create a new section at the end of this file with the title "Your work here", and beneath it, do the following 3 things. To turn this in, make sure you've committed and pushed, and turn in the link to this repository to the assignment on Blackboard.  

1. Make a subsection called Wise words. Put your favorite quote in a block quote. Add a functioning link to a website that provides more information about that quote.

2. Make a subsection called My semester. Make a three column table of the current courses you are taking, with separate columns for course number (put those in __bold__), course title (put those in _italics_), and instructor name.

3. Lastly, make subsection called "I recommend", and add some information about your favorite author or musician.

- A _subsubheading_ with the name of the artist or author;    
- An example of their writing or lyrics (formatted in a *block of text*);   
- A _list_ of things they have written or performed (remember to use the formatting markup for a list!).     


Note that you can click "Knit" as you go along to see what the final results are going to look like. The knitting will produce an html file, which you will also need to stage/commit/push once it exists! 

**Once you're done, remember to commit the changes and push the repo back to your assignment on GitHub!**
 
# Your Work Here

## Wise Words
> A Woman without a man is a like a fish without a bicycle -Gloria Steiman


[link] https://quoteinvestigator.com/2016/10/18/fish-bicycle/

## My Semester

Course Title | Course Number | Instructor Name
------------ |---------------| --------------
*Data Science 1* | **Data 2405** | Katherine Shoemaker
*Data Structures and Algorithm*| **CS 2311**   | John Hendrson
*Priciples of Economics* | **ECO 2301**  | Shuang Xu
*Texas Government* | **POLS 2306** | David Branham

## I Recommend

### Mariah The Scientist
Mariah The Scientist is an R&B singer best known for her song "Burning Blue". Her Upcoming Album HEARTS SOLD SEPARATELY features fellow R&B songstress Kali Uchis.

**_Songs to listen too_: **

* Beetlejuice
* Burning Blue
* Is it a Crime
* Spread Thin